import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {" "}
        <div className="h-screen w-full bg-cyan-300 absolute flex flex-col">
          <div className="flex-[1] w-full bg-orange-700"></div>
          <div className="flex-[8] w-full bg-orange-500">{children}</div>
          <div className="flex-[1] w-full bg-orange-700 flex items-center justify-center">
            <NavBar />
          </div>
        </div>
      </body>
    </html>
  );
}
